/**
 * File automatically generated by `typo` for its own test suite.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN
 */
package testdb
package postgres
package pg_catalog

import anorm.RowParser
import anorm.Success
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.Json
import play.api.libs.json.OFormat
import scala.util.Try

case class PgStatXactUserFunctionsRow(
  funcid: Option[/* oid */ Long],
  schemaname: Option[String],
  funcname: Option[String],
  calls: Option[Long],
  totalTime: Option[Double],
  selfTime: Option[Double]
)

object PgStatXactUserFunctionsRow {
  def rowParser(prefix: String): RowParser[PgStatXactUserFunctionsRow] = { row =>
    Success(
      PgStatXactUserFunctionsRow(
        funcid = row[Option[/* oid */ Long]](prefix + "funcid"),
        schemaname = row[Option[String]](prefix + "schemaname"),
        funcname = row[Option[String]](prefix + "funcname"),
        calls = row[Option[Long]](prefix + "calls"),
        totalTime = row[Option[Double]](prefix + "total_time"),
        selfTime = row[Option[Double]](prefix + "self_time")
      )
    )
  }

  implicit val oFormat: OFormat[PgStatXactUserFunctionsRow] = new OFormat[PgStatXactUserFunctionsRow]{
    override def writes(o: PgStatXactUserFunctionsRow): JsObject =
      Json.obj(
        "funcid" -> o.funcid,
      "schemaname" -> o.schemaname,
      "funcname" -> o.funcname,
      "calls" -> o.calls,
      "total_time" -> o.totalTime,
      "self_time" -> o.selfTime
      )

    override def reads(json: JsValue): JsResult[PgStatXactUserFunctionsRow] = {
      JsResult.fromTry(
        Try(
          PgStatXactUserFunctionsRow(
            funcid = json.\("funcid").toOption.map(_.as[/* oid */ Long]),
            schemaname = json.\("schemaname").toOption.map(_.as[String]),
            funcname = json.\("funcname").toOption.map(_.as[String]),
            calls = json.\("calls").toOption.map(_.as[Long]),
            totalTime = json.\("total_time").toOption.map(_.as[Double]),
            selfTime = json.\("self_time").toOption.map(_.as[Double])
          )
        )
      )
    }
  }
}
