/**
 * File automatically generated by `typo` for its own test suite.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN
 */
package testdb
package postgres
package pg_catalog

import java.sql.Connection

trait PgStatProgressCopyRepo {
  def selectAll(implicit c: Connection): List[PgStatProgressCopyRow]
  def selectByFieldValues(fieldValues: List[PgStatProgressCopyFieldValue[_]])(implicit c: Connection): List[PgStatProgressCopyRow]
}
