/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pg_catalog
package pg_statistic_ext

import typo.dsl.Bijection
import zio.json.JsonDecoder
import zio.json.JsonEncoder

/** Type for the primary key of table `pg_catalog.pg_statistic_ext` */
case class PgStatisticExtId(value: /* oid */ Long) extends AnyVal
object PgStatisticExtId {
  implicit lazy val bijection: Bijection[PgStatisticExtId, /* oid */ Long] = Bijection[PgStatisticExtId, /* oid */ Long](_.value)(PgStatisticExtId.apply)
  implicit lazy val decoder: JsonDecoder[PgStatisticExtId] = JsonDecoder.long.map(PgStatisticExtId.apply)
  implicit lazy val encoder: JsonEncoder[PgStatisticExtId] = JsonEncoder.long.contramap(_.value)
  implicit lazy val ordering: Ordering[PgStatisticExtId] = Ordering.by(_.value)
}
