/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pg_catalog
package pg_amop

import doobie.free.connection.ConnectionIO
import doobie.free.connection.delay
import fs2.Stream

class PgAmopRepoMock(map: scala.collection.mutable.Map[PgAmopId, PgAmopRow] = scala.collection.mutable.Map.empty) extends PgAmopRepo {
  override def delete(oid: PgAmopId): ConnectionIO[Boolean] = {
    delay(map.remove(oid).isDefined)
  }
  override def insert(unsaved: PgAmopRow): ConnectionIO[PgAmopRow] = {
    delay {
      if (map.contains(unsaved.oid))
        sys.error(s"id ${unsaved.oid} already exists")
      else
        map.put(unsaved.oid, unsaved)
      unsaved
    }
  }
  override def selectAll: Stream[ConnectionIO, PgAmopRow] = {
    Stream.emits(map.values.toList)
  }
  override def selectById(oid: PgAmopId): ConnectionIO[Option[PgAmopRow]] = {
    delay(map.get(oid))
  }
  override def selectByIds(oids: Array[PgAmopId]): Stream[ConnectionIO, PgAmopRow] = {
    Stream.emits(oids.flatMap(map.get).toList)
  }
  override def update(row: PgAmopRow): ConnectionIO[Boolean] = {
    delay {
      map.get(row.oid) match {
        case Some(`row`) => false
        case Some(_) =>
          map.put(row.oid, row)
          true
        case None => false
      }
    }
  }
  override def upsert(unsaved: PgAmopRow): ConnectionIO[PgAmopRow] = {
    delay {
      map.put(unsaved.oid, unsaved)
      unsaved
    }
  }
}
