/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.pe.bea;

import typo.dsl.SelectBuilder;
import zio.jdbc.ZConnection;
import zio.stream.ZStream;

trait BeaViewRepo {
  def select: SelectBuilder[BeaViewFields, BeaViewRow]
  def selectAll: ZStream[ZConnection, Throwable, BeaViewRow]
}