/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package sa
package sohsr

import adventureworks.sales.salesorderheader.SalesorderheaderId
import adventureworks.sales.salesreason.SalesreasonId
import java.time.LocalDateTime

sealed abstract class SohsrFieldOrIdValue[T](val name: String, val value: T)
sealed abstract class SohsrFieldValue[T](name: String, value: T) extends SohsrFieldOrIdValue(name, value)

object SohsrFieldValue {
  case class salesorderid(override val value: Option[SalesorderheaderId]) extends SohsrFieldValue("salesorderid", value)
  case class salesreasonid(override val value: Option[SalesreasonId]) extends SohsrFieldValue("salesreasonid", value)
  case class modifieddate(override val value: Option[LocalDateTime]) extends SohsrFieldValue("modifieddate", value)
}
