/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pg_catalog
package pg_amop

import anorm.SqlStringInterpolation
import java.sql.Connection

object PgAmopRepoImpl extends PgAmopRepo {
  override def delete(oid: PgAmopId)(implicit c: Connection): Boolean = {
    SQL"delete from pg_catalog.pg_amop where oid = $oid".executeUpdate() > 0
  }
  override def insert(unsaved: PgAmopRow)(implicit c: Connection): PgAmopRow = {
    SQL"""insert into pg_catalog.pg_amop(oid, amopfamily, amoplefttype, amoprighttype, amopstrategy, amoppurpose, amopopr, amopmethod, amopsortfamily)
          values (${unsaved.oid}::oid, ${unsaved.amopfamily}::oid, ${unsaved.amoplefttype}::oid, ${unsaved.amoprighttype}::oid, ${unsaved.amopstrategy}::int2, ${unsaved.amoppurpose}::char, ${unsaved.amopopr}::oid, ${unsaved.amopmethod}::oid, ${unsaved.amopsortfamily}::oid)
          returning oid, amopfamily, amoplefttype, amoprighttype, amopstrategy, amoppurpose, amopopr, amopmethod, amopsortfamily
       """
      .executeInsert(PgAmopRow.rowParser(1).single)
    
  }
  override def selectAll(implicit c: Connection): List[PgAmopRow] = {
    SQL"""select oid, amopfamily, amoplefttype, amoprighttype, amopstrategy, amoppurpose, amopopr, amopmethod, amopsortfamily
          from pg_catalog.pg_amop
       """.as(PgAmopRow.rowParser(1).*)
  }
  override def selectById(oid: PgAmopId)(implicit c: Connection): Option[PgAmopRow] = {
    SQL"""select oid, amopfamily, amoplefttype, amoprighttype, amopstrategy, amoppurpose, amopopr, amopmethod, amopsortfamily
          from pg_catalog.pg_amop
          where oid = $oid
       """.as(PgAmopRow.rowParser(1).singleOpt)
  }
  override def selectByIds(oids: Array[PgAmopId])(implicit c: Connection): List[PgAmopRow] = {
    SQL"""select oid, amopfamily, amoplefttype, amoprighttype, amopstrategy, amoppurpose, amopopr, amopmethod, amopsortfamily
          from pg_catalog.pg_amop
          where oid = ANY($oids)
       """.as(PgAmopRow.rowParser(1).*)
    
  }
  override def update(row: PgAmopRow)(implicit c: Connection): Boolean = {
    val oid = row.oid
    SQL"""update pg_catalog.pg_amop
          set amopfamily = ${row.amopfamily}::oid,
              amoplefttype = ${row.amoplefttype}::oid,
              amoprighttype = ${row.amoprighttype}::oid,
              amopstrategy = ${row.amopstrategy}::int2,
              amoppurpose = ${row.amoppurpose}::char,
              amopopr = ${row.amopopr}::oid,
              amopmethod = ${row.amopmethod}::oid,
              amopsortfamily = ${row.amopsortfamily}::oid
          where oid = $oid
       """.executeUpdate() > 0
  }
  override def upsert(unsaved: PgAmopRow)(implicit c: Connection): PgAmopRow = {
    SQL"""insert into pg_catalog.pg_amop(oid, amopfamily, amoplefttype, amoprighttype, amopstrategy, amoppurpose, amopopr, amopmethod, amopsortfamily)
          values (
            ${unsaved.oid}::oid,
            ${unsaved.amopfamily}::oid,
            ${unsaved.amoplefttype}::oid,
            ${unsaved.amoprighttype}::oid,
            ${unsaved.amopstrategy}::int2,
            ${unsaved.amoppurpose}::char,
            ${unsaved.amopopr}::oid,
            ${unsaved.amopmethod}::oid,
            ${unsaved.amopsortfamily}::oid
          )
          on conflict (oid)
          do update set
            amopfamily = EXCLUDED.amopfamily,
            amoplefttype = EXCLUDED.amoplefttype,
            amoprighttype = EXCLUDED.amoprighttype,
            amopstrategy = EXCLUDED.amopstrategy,
            amoppurpose = EXCLUDED.amoppurpose,
            amopopr = EXCLUDED.amopopr,
            amopmethod = EXCLUDED.amopmethod,
            amopsortfamily = EXCLUDED.amopsortfamily
          returning oid, amopfamily, amoplefttype, amoprighttype, amopstrategy, amoppurpose, amopopr, amopmethod, amopsortfamily
       """
      .executeInsert(PgAmopRow.rowParser(1).single)
    
  }
}
