/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package information_schema
package attributes

import doobie.enumerated.Nullability
import doobie.util.Read
import doobie.util.meta.Meta
import io.circe.Decoder
import io.circe.DecodingFailure
import io.circe.Encoder
import io.circe.HCursor
import io.circe.Json
import java.sql.ResultSet
import scala.util.Try

case class AttributesViewRow(
  udtCatalog: /* nullability unknown */ Option[String],
  udtSchema: /* nullability unknown */ Option[String],
  udtName: /* nullability unknown */ Option[String],
  attributeName: /* nullability unknown */ Option[String],
  ordinalPosition: /* nullability unknown */ Option[Int],
  attributeDefault: /* nullability unknown */ Option[String],
  isNullable: /* nullability unknown */ Option[/* max 3 chars */ String],
  dataType: /* nullability unknown */ Option[String],
  characterMaximumLength: /* nullability unknown */ Option[Int],
  characterOctetLength: /* nullability unknown */ Option[Int],
  characterSetCatalog: /* nullability unknown */ Option[String],
  characterSetSchema: /* nullability unknown */ Option[String],
  characterSetName: /* nullability unknown */ Option[String],
  collationCatalog: /* nullability unknown */ Option[String],
  collationSchema: /* nullability unknown */ Option[String],
  collationName: /* nullability unknown */ Option[String],
  numericPrecision: /* nullability unknown */ Option[Int],
  numericPrecisionRadix: /* nullability unknown */ Option[Int],
  numericScale: /* nullability unknown */ Option[Int],
  datetimePrecision: /* nullability unknown */ Option[Int],
  intervalType: /* nullability unknown */ Option[String],
  intervalPrecision: /* nullability unknown */ Option[Int],
  attributeUdtCatalog: /* nullability unknown */ Option[String],
  attributeUdtSchema: /* nullability unknown */ Option[String],
  attributeUdtName: /* nullability unknown */ Option[String],
  scopeCatalog: /* nullability unknown */ Option[String],
  scopeSchema: /* nullability unknown */ Option[String],
  scopeName: /* nullability unknown */ Option[String],
  maximumCardinality: /* nullability unknown */ Option[Int],
  dtdIdentifier: /* nullability unknown */ Option[String],
  isDerivedReferenceAttribute: /* nullability unknown */ Option[/* max 3 chars */ String]
)

object AttributesViewRow {
  implicit lazy val decoder: Decoder[AttributesViewRow] = Decoder.instanceTry[AttributesViewRow]((c: HCursor) =>
    Try {
      def orThrow[R](either: Either[DecodingFailure, R]): R = either match {
        case Left(err) => throw err
        case Right(r)  => r
      }
      AttributesViewRow(
        udtCatalog = orThrow(c.get("udt_catalog")(Decoder.decodeOption(Decoder.decodeString))),
        udtSchema = orThrow(c.get("udt_schema")(Decoder.decodeOption(Decoder.decodeString))),
        udtName = orThrow(c.get("udt_name")(Decoder.decodeOption(Decoder.decodeString))),
        attributeName = orThrow(c.get("attribute_name")(Decoder.decodeOption(Decoder.decodeString))),
        ordinalPosition = orThrow(c.get("ordinal_position")(Decoder.decodeOption(Decoder.decodeInt))),
        attributeDefault = orThrow(c.get("attribute_default")(Decoder.decodeOption(Decoder.decodeString))),
        isNullable = orThrow(c.get("is_nullable")(Decoder.decodeOption(Decoder.decodeString))),
        dataType = orThrow(c.get("data_type")(Decoder.decodeOption(Decoder.decodeString))),
        characterMaximumLength = orThrow(c.get("character_maximum_length")(Decoder.decodeOption(Decoder.decodeInt))),
        characterOctetLength = orThrow(c.get("character_octet_length")(Decoder.decodeOption(Decoder.decodeInt))),
        characterSetCatalog = orThrow(c.get("character_set_catalog")(Decoder.decodeOption(Decoder.decodeString))),
        characterSetSchema = orThrow(c.get("character_set_schema")(Decoder.decodeOption(Decoder.decodeString))),
        characterSetName = orThrow(c.get("character_set_name")(Decoder.decodeOption(Decoder.decodeString))),
        collationCatalog = orThrow(c.get("collation_catalog")(Decoder.decodeOption(Decoder.decodeString))),
        collationSchema = orThrow(c.get("collation_schema")(Decoder.decodeOption(Decoder.decodeString))),
        collationName = orThrow(c.get("collation_name")(Decoder.decodeOption(Decoder.decodeString))),
        numericPrecision = orThrow(c.get("numeric_precision")(Decoder.decodeOption(Decoder.decodeInt))),
        numericPrecisionRadix = orThrow(c.get("numeric_precision_radix")(Decoder.decodeOption(Decoder.decodeInt))),
        numericScale = orThrow(c.get("numeric_scale")(Decoder.decodeOption(Decoder.decodeInt))),
        datetimePrecision = orThrow(c.get("datetime_precision")(Decoder.decodeOption(Decoder.decodeInt))),
        intervalType = orThrow(c.get("interval_type")(Decoder.decodeOption(Decoder.decodeString))),
        intervalPrecision = orThrow(c.get("interval_precision")(Decoder.decodeOption(Decoder.decodeInt))),
        attributeUdtCatalog = orThrow(c.get("attribute_udt_catalog")(Decoder.decodeOption(Decoder.decodeString))),
        attributeUdtSchema = orThrow(c.get("attribute_udt_schema")(Decoder.decodeOption(Decoder.decodeString))),
        attributeUdtName = orThrow(c.get("attribute_udt_name")(Decoder.decodeOption(Decoder.decodeString))),
        scopeCatalog = orThrow(c.get("scope_catalog")(Decoder.decodeOption(Decoder.decodeString))),
        scopeSchema = orThrow(c.get("scope_schema")(Decoder.decodeOption(Decoder.decodeString))),
        scopeName = orThrow(c.get("scope_name")(Decoder.decodeOption(Decoder.decodeString))),
        maximumCardinality = orThrow(c.get("maximum_cardinality")(Decoder.decodeOption(Decoder.decodeInt))),
        dtdIdentifier = orThrow(c.get("dtd_identifier")(Decoder.decodeOption(Decoder.decodeString))),
        isDerivedReferenceAttribute = orThrow(c.get("is_derived_reference_attribute")(Decoder.decodeOption(Decoder.decodeString)))
      )
    }
  )
  implicit lazy val encoder: Encoder[AttributesViewRow] = Encoder[AttributesViewRow](row =>
    Json.obj(
      "udt_catalog" -> Encoder.encodeOption(Encoder.encodeString).apply(row.udtCatalog),
      "udt_schema" -> Encoder.encodeOption(Encoder.encodeString).apply(row.udtSchema),
      "udt_name" -> Encoder.encodeOption(Encoder.encodeString).apply(row.udtName),
      "attribute_name" -> Encoder.encodeOption(Encoder.encodeString).apply(row.attributeName),
      "ordinal_position" -> Encoder.encodeOption(Encoder.encodeInt).apply(row.ordinalPosition),
      "attribute_default" -> Encoder.encodeOption(Encoder.encodeString).apply(row.attributeDefault),
      "is_nullable" -> Encoder.encodeOption(Encoder.encodeString).apply(row.isNullable),
      "data_type" -> Encoder.encodeOption(Encoder.encodeString).apply(row.dataType),
      "character_maximum_length" -> Encoder.encodeOption(Encoder.encodeInt).apply(row.characterMaximumLength),
      "character_octet_length" -> Encoder.encodeOption(Encoder.encodeInt).apply(row.characterOctetLength),
      "character_set_catalog" -> Encoder.encodeOption(Encoder.encodeString).apply(row.characterSetCatalog),
      "character_set_schema" -> Encoder.encodeOption(Encoder.encodeString).apply(row.characterSetSchema),
      "character_set_name" -> Encoder.encodeOption(Encoder.encodeString).apply(row.characterSetName),
      "collation_catalog" -> Encoder.encodeOption(Encoder.encodeString).apply(row.collationCatalog),
      "collation_schema" -> Encoder.encodeOption(Encoder.encodeString).apply(row.collationSchema),
      "collation_name" -> Encoder.encodeOption(Encoder.encodeString).apply(row.collationName),
      "numeric_precision" -> Encoder.encodeOption(Encoder.encodeInt).apply(row.numericPrecision),
      "numeric_precision_radix" -> Encoder.encodeOption(Encoder.encodeInt).apply(row.numericPrecisionRadix),
      "numeric_scale" -> Encoder.encodeOption(Encoder.encodeInt).apply(row.numericScale),
      "datetime_precision" -> Encoder.encodeOption(Encoder.encodeInt).apply(row.datetimePrecision),
      "interval_type" -> Encoder.encodeOption(Encoder.encodeString).apply(row.intervalType),
      "interval_precision" -> Encoder.encodeOption(Encoder.encodeInt).apply(row.intervalPrecision),
      "attribute_udt_catalog" -> Encoder.encodeOption(Encoder.encodeString).apply(row.attributeUdtCatalog),
      "attribute_udt_schema" -> Encoder.encodeOption(Encoder.encodeString).apply(row.attributeUdtSchema),
      "attribute_udt_name" -> Encoder.encodeOption(Encoder.encodeString).apply(row.attributeUdtName),
      "scope_catalog" -> Encoder.encodeOption(Encoder.encodeString).apply(row.scopeCatalog),
      "scope_schema" -> Encoder.encodeOption(Encoder.encodeString).apply(row.scopeSchema),
      "scope_name" -> Encoder.encodeOption(Encoder.encodeString).apply(row.scopeName),
      "maximum_cardinality" -> Encoder.encodeOption(Encoder.encodeInt).apply(row.maximumCardinality),
      "dtd_identifier" -> Encoder.encodeOption(Encoder.encodeString).apply(row.dtdIdentifier),
      "is_derived_reference_attribute" -> Encoder.encodeOption(Encoder.encodeString).apply(row.isDerivedReferenceAttribute)
    )
  )
  implicit lazy val read: Read[AttributesViewRow] = new Read[AttributesViewRow](
    gets = List(
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.IntMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.IntMeta.get, Nullability.Nullable),
      (Meta.IntMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.IntMeta.get, Nullability.Nullable),
      (Meta.IntMeta.get, Nullability.Nullable),
      (Meta.IntMeta.get, Nullability.Nullable),
      (Meta.IntMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.IntMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.IntMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable),
      (Meta.StringMeta.get, Nullability.Nullable)
    ),
    unsafeGet = (rs: ResultSet, i: Int) => AttributesViewRow(
      udtCatalog = Meta.StringMeta.get.unsafeGetNullable(rs, i + 0),
      udtSchema = Meta.StringMeta.get.unsafeGetNullable(rs, i + 1),
      udtName = Meta.StringMeta.get.unsafeGetNullable(rs, i + 2),
      attributeName = Meta.StringMeta.get.unsafeGetNullable(rs, i + 3),
      ordinalPosition = Meta.IntMeta.get.unsafeGetNullable(rs, i + 4),
      attributeDefault = Meta.StringMeta.get.unsafeGetNullable(rs, i + 5),
      isNullable = Meta.StringMeta.get.unsafeGetNullable(rs, i + 6),
      dataType = Meta.StringMeta.get.unsafeGetNullable(rs, i + 7),
      characterMaximumLength = Meta.IntMeta.get.unsafeGetNullable(rs, i + 8),
      characterOctetLength = Meta.IntMeta.get.unsafeGetNullable(rs, i + 9),
      characterSetCatalog = Meta.StringMeta.get.unsafeGetNullable(rs, i + 10),
      characterSetSchema = Meta.StringMeta.get.unsafeGetNullable(rs, i + 11),
      characterSetName = Meta.StringMeta.get.unsafeGetNullable(rs, i + 12),
      collationCatalog = Meta.StringMeta.get.unsafeGetNullable(rs, i + 13),
      collationSchema = Meta.StringMeta.get.unsafeGetNullable(rs, i + 14),
      collationName = Meta.StringMeta.get.unsafeGetNullable(rs, i + 15),
      numericPrecision = Meta.IntMeta.get.unsafeGetNullable(rs, i + 16),
      numericPrecisionRadix = Meta.IntMeta.get.unsafeGetNullable(rs, i + 17),
      numericScale = Meta.IntMeta.get.unsafeGetNullable(rs, i + 18),
      datetimePrecision = Meta.IntMeta.get.unsafeGetNullable(rs, i + 19),
      intervalType = Meta.StringMeta.get.unsafeGetNullable(rs, i + 20),
      intervalPrecision = Meta.IntMeta.get.unsafeGetNullable(rs, i + 21),
      attributeUdtCatalog = Meta.StringMeta.get.unsafeGetNullable(rs, i + 22),
      attributeUdtSchema = Meta.StringMeta.get.unsafeGetNullable(rs, i + 23),
      attributeUdtName = Meta.StringMeta.get.unsafeGetNullable(rs, i + 24),
      scopeCatalog = Meta.StringMeta.get.unsafeGetNullable(rs, i + 25),
      scopeSchema = Meta.StringMeta.get.unsafeGetNullable(rs, i + 26),
      scopeName = Meta.StringMeta.get.unsafeGetNullable(rs, i + 27),
      maximumCardinality = Meta.IntMeta.get.unsafeGetNullable(rs, i + 28),
      dtdIdentifier = Meta.StringMeta.get.unsafeGetNullable(rs, i + 29),
      isDerivedReferenceAttribute = Meta.StringMeta.get.unsafeGetNullable(rs, i + 30)
    )
  )
}
