/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pg_catalog
package pg_ts_parser

import adventureworks.TypoRegproc
import doobie.enumerated.Nullability
import doobie.util.Get
import doobie.util.Read
import io.circe.Decoder
import io.circe.Encoder
import java.sql.ResultSet

case class PgTsParserRow(
  oid: PgTsParserId,
  prsname: String,
  prsnamespace: /* oid */ Long,
  prsstart: TypoRegproc,
  prstoken: TypoRegproc,
  prsend: TypoRegproc,
  prsheadline: TypoRegproc,
  prslextype: TypoRegproc
)

object PgTsParserRow {
  implicit val decoder: Decoder[PgTsParserRow] = Decoder.forProduct8[PgTsParserRow, PgTsParserId, String, /* oid */ Long, TypoRegproc, TypoRegproc, TypoRegproc, TypoRegproc, TypoRegproc]("oid", "prsname", "prsnamespace", "prsstart", "prstoken", "prsend", "prsheadline", "prslextype")(PgTsParserRow.apply)
  implicit val encoder: Encoder[PgTsParserRow] = Encoder.forProduct8[PgTsParserRow, PgTsParserId, String, /* oid */ Long, TypoRegproc, TypoRegproc, TypoRegproc, TypoRegproc, TypoRegproc]("oid", "prsname", "prsnamespace", "prsstart", "prstoken", "prsend", "prsheadline", "prslextype")(x => (x.oid, x.prsname, x.prsnamespace, x.prsstart, x.prstoken, x.prsend, x.prsheadline, x.prslextype))
  implicit val read: Read[PgTsParserRow] = new Read[PgTsParserRow](
    gets = List(
      (Get[PgTsParserId], Nullability.NoNulls),
      (Get[String], Nullability.NoNulls),
      (Get[/* oid */ Long], Nullability.NoNulls),
      (Get[TypoRegproc], Nullability.NoNulls),
      (Get[TypoRegproc], Nullability.NoNulls),
      (Get[TypoRegproc], Nullability.NoNulls),
      (Get[TypoRegproc], Nullability.NoNulls),
      (Get[TypoRegproc], Nullability.NoNulls)
    ),
    unsafeGet = (rs: ResultSet, i: Int) => PgTsParserRow(
      oid = Get[PgTsParserId].unsafeGetNonNullable(rs, i + 0),
      prsname = Get[String].unsafeGetNonNullable(rs, i + 1),
      prsnamespace = Get[/* oid */ Long].unsafeGetNonNullable(rs, i + 2),
      prsstart = Get[TypoRegproc].unsafeGetNonNullable(rs, i + 3),
      prstoken = Get[TypoRegproc].unsafeGetNonNullable(rs, i + 4),
      prsend = Get[TypoRegproc].unsafeGetNonNullable(rs, i + 5),
      prsheadline = Get[TypoRegproc].unsafeGetNonNullable(rs, i + 6),
      prslextype = Get[TypoRegproc].unsafeGetNonNullable(rs, i + 7)
    )
  )
}
