/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pr
package w

import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.production.product.ProductId
import adventureworks.production.scrapreason.ScrapreasonId
import adventureworks.production.workorder.WorkorderId
import typo.dsl.SqlExpr.Field
import typo.dsl.SqlExpr.OptField

trait WViewFields[Row] {
  val id: Field[WorkorderId, Row]
  val workorderid: Field[WorkorderId, Row]
  val productid: Field[ProductId, Row]
  val orderqty: Field[Int, Row]
  val scrappedqty: Field[Int, Row]
  val startdate: Field[TypoLocalDateTime, Row]
  val enddate: OptField[TypoLocalDateTime, Row]
  val duedate: Field[TypoLocalDateTime, Row]
  val scrapreasonid: OptField[ScrapreasonId, Row]
  val modifieddate: Field[TypoLocalDateTime, Row]
}
object WViewFields extends WViewStructure[WViewRow](None, identity, (_, x) => x)

