/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pg_catalog
package pg_cursors

import java.sql.Connection
import typo.dsl.SelectBuilder

trait PgCursorsViewRepo {
  def select: SelectBuilder[PgCursorsViewFields, PgCursorsViewRow]
  def selectAll(implicit c: Connection): List[PgCursorsViewRow]
}
