# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: ghcr.io/oyvindberg/typo/typo-postgres${PG_MAJOR-16}:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: world
    platform: linux/x86_64
    ports:
      - 6432:5432
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
