# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgis/postgis:14-3.3 # postgres with postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: world
    ports:
      - 6432:5432
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
