# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: ghcr.io/oyvindberg/typo/integration-test:main
    # TODO switch to new images depending on PG_MAJOR once we've pushed them
    # image: ghcr.io/oyvindberg/typo/typo-postgres${PG_MAJOR}:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: world
    ports:
      - 6432:5432
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
