/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package information_schema
package column_udt_usage

import adventureworks.information_schema.SqlIdentifier
import anorm.RowParser
import anorm.Success
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.Json
import play.api.libs.json.OWrites
import play.api.libs.json.Reads
import scala.collection.immutable.ListMap
import scala.util.Try

case class ColumnUdtUsageViewRow(
  udtCatalog: Option[SqlIdentifier],
  udtSchema: Option[SqlIdentifier],
  udtName: Option[SqlIdentifier],
  tableCatalog: Option[SqlIdentifier],
  tableSchema: Option[SqlIdentifier],
  tableName: Option[SqlIdentifier],
  columnName: Option[SqlIdentifier]
)

object ColumnUdtUsageViewRow {
  implicit val reads: Reads[ColumnUdtUsageViewRow] = Reads[ColumnUdtUsageViewRow](json => JsResult.fromTry(
      Try(
        ColumnUdtUsageViewRow(
          udtCatalog = json.\("udt_catalog").toOption.map(_.as[SqlIdentifier]),
          udtSchema = json.\("udt_schema").toOption.map(_.as[SqlIdentifier]),
          udtName = json.\("udt_name").toOption.map(_.as[SqlIdentifier]),
          tableCatalog = json.\("table_catalog").toOption.map(_.as[SqlIdentifier]),
          tableSchema = json.\("table_schema").toOption.map(_.as[SqlIdentifier]),
          tableName = json.\("table_name").toOption.map(_.as[SqlIdentifier]),
          columnName = json.\("column_name").toOption.map(_.as[SqlIdentifier])
        )
      )
    ),
  )
  def rowParser(idx: Int): RowParser[ColumnUdtUsageViewRow] = RowParser[ColumnUdtUsageViewRow] { row =>
    Success(
      ColumnUdtUsageViewRow(
        udtCatalog = row[Option[SqlIdentifier]](idx + 0),
        udtSchema = row[Option[SqlIdentifier]](idx + 1),
        udtName = row[Option[SqlIdentifier]](idx + 2),
        tableCatalog = row[Option[SqlIdentifier]](idx + 3),
        tableSchema = row[Option[SqlIdentifier]](idx + 4),
        tableName = row[Option[SqlIdentifier]](idx + 5),
        columnName = row[Option[SqlIdentifier]](idx + 6)
      )
    )
  }
  implicit val writes: OWrites[ColumnUdtUsageViewRow] = OWrites[ColumnUdtUsageViewRow](o =>
    new JsObject(ListMap[String, JsValue](
      "udt_catalog" -> Json.toJson(o.udtCatalog),
      "udt_schema" -> Json.toJson(o.udtSchema),
      "udt_name" -> Json.toJson(o.udtName),
      "table_catalog" -> Json.toJson(o.tableCatalog),
      "table_schema" -> Json.toJson(o.tableSchema),
      "table_name" -> Json.toJson(o.tableName),
      "column_name" -> Json.toJson(o.columnName)
    ))
  )
}
