/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package information_schema
package udt_privileges

import java.sql.Connection

trait UdtPrivilegesViewRepo {
  def selectAll(implicit c: Connection): List[UdtPrivilegesViewRow]
}
