/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package information_schema
package enabled_roles

import java.sql.Connection
import typo.dsl.SelectBuilder

trait EnabledRolesViewRepo {
  def select: SelectBuilder[EnabledRolesViewFields, EnabledRolesViewRow]
  def selectAll(implicit c: Connection): List[EnabledRolesViewRow]
}
