/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package frontpage
package order_item

import adventureworks.customtypes.Defaulted
import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.frontpage.order.OrderId
import adventureworks.frontpage.product.ProductId
import cats.instances.list.catsStdInstancesForList
import doobie.free.connection.ConnectionIO
import doobie.postgres.syntax.FragmentOps
import doobie.syntax.SqlInterpolator.SingleFragment.fromWrite
import doobie.syntax.string.toSqlInterpolator
import doobie.util.Write
import doobie.util.fragment.Fragment
import doobie.util.meta.Meta
import doobie.util.update.Update
import fs2.Stream
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.SelectBuilderSql
import typo.dsl.UpdateBuilder

class OrderItemRepoImpl extends OrderItemRepo {
  override def delete: DeleteBuilder[OrderItemFields, OrderItemRow] = {
    DeleteBuilder(""""frontpage"."order_item"""", OrderItemFields.structure)
  }
  override def deleteById(id: OrderItemId): ConnectionIO[Boolean] = {
    sql"""delete from "frontpage"."order_item" where "id" = ${fromWrite(id)(new Write.Single(OrderItemId.put))}""".update.run.map(_ > 0)
  }
  override def deleteByIds(ids: Array[OrderItemId]): ConnectionIO[Int] = {
    sql"""delete from "frontpage"."order_item" where "id" = ANY(${ids})""".update.run
  }
  override def insert(unsaved: OrderItemRow): ConnectionIO[OrderItemRow] = {
    sql"""insert into "frontpage"."order_item"("id", "order_id", "product_id", "quantity", "price", "shipped_at")
          values (${fromWrite(unsaved.id)(new Write.Single(OrderItemId.put))}::uuid, ${fromWrite(unsaved.orderId)(new Write.SingleOpt(OrderId.put))}::uuid, ${fromWrite(unsaved.productId)(new Write.SingleOpt(ProductId.put))}::uuid, ${fromWrite(unsaved.quantity)(new Write.Single(Meta.IntMeta.put))}::int4, ${fromWrite(unsaved.price)(new Write.Single(Meta.ScalaBigDecimalMeta.put))}::numeric, ${fromWrite(unsaved.shippedAt)(new Write.SingleOpt(TypoLocalDateTime.put))}::timestamp)
          returning "id", "order_id", "product_id", "quantity", "price", "shipped_at"::text
       """.query(using OrderItemRow.read).unique
  }
  override def insert(unsaved: OrderItemRowUnsaved): ConnectionIO[OrderItemRow] = {
    val fs = List(
      Some((Fragment.const0(s""""order_id""""), fr"${fromWrite(unsaved.orderId)(new Write.SingleOpt(OrderId.put))}::uuid")),
      Some((Fragment.const0(s""""product_id""""), fr"${fromWrite(unsaved.productId)(new Write.SingleOpt(ProductId.put))}::uuid")),
      Some((Fragment.const0(s""""quantity""""), fr"${fromWrite(unsaved.quantity)(new Write.Single(Meta.IntMeta.put))}::int4")),
      Some((Fragment.const0(s""""price""""), fr"${fromWrite(unsaved.price)(new Write.Single(Meta.ScalaBigDecimalMeta.put))}::numeric")),
      Some((Fragment.const0(s""""shipped_at""""), fr"${fromWrite(unsaved.shippedAt)(new Write.SingleOpt(TypoLocalDateTime.put))}::timestamp")),
      unsaved.id match {
        case Defaulted.UseDefault => None
        case Defaulted.Provided(value) => Some((Fragment.const0(s""""id""""), fr"${fromWrite(value: OrderItemId)(new Write.Single(OrderItemId.put))}::uuid"))
      }
    ).flatten
    
    val q = if (fs.isEmpty) {
      sql"""insert into "frontpage"."order_item" default values
            returning "id", "order_id", "product_id", "quantity", "price", "shipped_at"::text
         """
    } else {
      val CommaSeparate = Fragment.FragmentMonoid.intercalate(fr", ")
      sql"""insert into "frontpage"."order_item"(${CommaSeparate.combineAllOption(fs.map { case (n, _) => n }).get})
            values (${CommaSeparate.combineAllOption(fs.map { case (_, f) => f }).get})
            returning "id", "order_id", "product_id", "quantity", "price", "shipped_at"::text
         """
    }
    q.query(using OrderItemRow.read).unique
    
  }
  override def insertStreaming(unsaved: Stream[ConnectionIO, OrderItemRow], batchSize: Int = 10000): ConnectionIO[Long] = {
    new FragmentOps(sql"""COPY "frontpage"."order_item"("id", "order_id", "product_id", "quantity", "price", "shipped_at") FROM STDIN""").copyIn(unsaved, batchSize)(using OrderItemRow.text)
  }
  /* NOTE: this functionality requires PostgreSQL 16 or later! */
  override def insertUnsavedStreaming(unsaved: Stream[ConnectionIO, OrderItemRowUnsaved], batchSize: Int = 10000): ConnectionIO[Long] = {
    new FragmentOps(sql"""COPY "frontpage"."order_item"("order_id", "product_id", "quantity", "price", "shipped_at", "id") FROM STDIN (DEFAULT '__DEFAULT_VALUE__')""").copyIn(unsaved, batchSize)(using OrderItemRowUnsaved.text)
  }
  override def select: SelectBuilder[OrderItemFields, OrderItemRow] = {
    SelectBuilderSql(""""frontpage"."order_item"""", OrderItemFields.structure, OrderItemRow.read)
  }
  override def selectAll: Stream[ConnectionIO, OrderItemRow] = {
    sql"""select "id", "order_id", "product_id", "quantity", "price", "shipped_at"::text from "frontpage"."order_item"""".query(using OrderItemRow.read).stream
  }
  override def selectById(id: OrderItemId): ConnectionIO[Option[OrderItemRow]] = {
    sql"""select "id", "order_id", "product_id", "quantity", "price", "shipped_at"::text from "frontpage"."order_item" where "id" = ${fromWrite(id)(new Write.Single(OrderItemId.put))}""".query(using OrderItemRow.read).option
  }
  override def selectByIds(ids: Array[OrderItemId]): Stream[ConnectionIO, OrderItemRow] = {
    sql"""select "id", "order_id", "product_id", "quantity", "price", "shipped_at"::text from "frontpage"."order_item" where "id" = ANY(${ids})""".query(using OrderItemRow.read).stream
  }
  override def selectByIdsTracked(ids: Array[OrderItemId]): ConnectionIO[Map[OrderItemId, OrderItemRow]] = {
    selectByIds(ids).compile.toList.map { rows =>
      val byId = rows.view.map(x => (x.id, x)).toMap
      ids.view.flatMap(id => byId.get(id).map(x => (id, x))).toMap
    }
  }
  override def update: UpdateBuilder[OrderItemFields, OrderItemRow] = {
    UpdateBuilder(""""frontpage"."order_item"""", OrderItemFields.structure, OrderItemRow.read)
  }
  override def update(row: OrderItemRow): ConnectionIO[Boolean] = {
    val id = row.id
    sql"""update "frontpage"."order_item"
          set "order_id" = ${fromWrite(row.orderId)(new Write.SingleOpt(OrderId.put))}::uuid,
              "product_id" = ${fromWrite(row.productId)(new Write.SingleOpt(ProductId.put))}::uuid,
              "quantity" = ${fromWrite(row.quantity)(new Write.Single(Meta.IntMeta.put))}::int4,
              "price" = ${fromWrite(row.price)(new Write.Single(Meta.ScalaBigDecimalMeta.put))}::numeric,
              "shipped_at" = ${fromWrite(row.shippedAt)(new Write.SingleOpt(TypoLocalDateTime.put))}::timestamp
          where "id" = ${fromWrite(id)(new Write.Single(OrderItemId.put))}"""
      .update
      .run
      .map(_ > 0)
  }
  override def upsert(unsaved: OrderItemRow): ConnectionIO[OrderItemRow] = {
    sql"""insert into "frontpage"."order_item"("id", "order_id", "product_id", "quantity", "price", "shipped_at")
          values (
            ${fromWrite(unsaved.id)(new Write.Single(OrderItemId.put))}::uuid,
            ${fromWrite(unsaved.orderId)(new Write.SingleOpt(OrderId.put))}::uuid,
            ${fromWrite(unsaved.productId)(new Write.SingleOpt(ProductId.put))}::uuid,
            ${fromWrite(unsaved.quantity)(new Write.Single(Meta.IntMeta.put))}::int4,
            ${fromWrite(unsaved.price)(new Write.Single(Meta.ScalaBigDecimalMeta.put))}::numeric,
            ${fromWrite(unsaved.shippedAt)(new Write.SingleOpt(TypoLocalDateTime.put))}::timestamp
          )
          on conflict ("id")
          do update set
            "order_id" = EXCLUDED."order_id",
            "product_id" = EXCLUDED."product_id",
            "quantity" = EXCLUDED."quantity",
            "price" = EXCLUDED."price",
            "shipped_at" = EXCLUDED."shipped_at"
          returning "id", "order_id", "product_id", "quantity", "price", "shipped_at"::text
       """.query(using OrderItemRow.read).unique
  }
  override def upsertBatch(unsaved: List[OrderItemRow]): Stream[ConnectionIO, OrderItemRow] = {
    Update[OrderItemRow](
      s"""insert into "frontpage"."order_item"("id", "order_id", "product_id", "quantity", "price", "shipped_at")
          values (?::uuid,?::uuid,?::uuid,?::int4,?::numeric,?::timestamp)
          on conflict ("id")
          do update set
            "order_id" = EXCLUDED."order_id",
            "product_id" = EXCLUDED."product_id",
            "quantity" = EXCLUDED."quantity",
            "price" = EXCLUDED."price",
            "shipped_at" = EXCLUDED."shipped_at"
          returning "id", "order_id", "product_id", "quantity", "price", "shipped_at"::text"""
    )(using OrderItemRow.write)
    .updateManyWithGeneratedKeys[OrderItemRow]("id", "order_id", "product_id", "quantity", "price", "shipped_at")(unsaved)(using catsStdInstancesForList, OrderItemRow.read)
  }
  /* NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  override def upsertStreaming(unsaved: Stream[ConnectionIO, OrderItemRow], batchSize: Int = 10000): ConnectionIO[Int] = {
    for {
      _ <- sql"""create temporary table order_item_TEMP (like "frontpage"."order_item") on commit drop""".update.run
      _ <- new FragmentOps(sql"""copy order_item_TEMP("id", "order_id", "product_id", "quantity", "price", "shipped_at") from stdin""").copyIn(unsaved, batchSize)(using OrderItemRow.text)
      res <- sql"""insert into "frontpage"."order_item"("id", "order_id", "product_id", "quantity", "price", "shipped_at")
                   select * from order_item_TEMP
                   on conflict ("id")
                   do update set
                     "order_id" = EXCLUDED."order_id",
                     "product_id" = EXCLUDED."product_id",
                     "quantity" = EXCLUDED."quantity",
                     "price" = EXCLUDED."price",
                     "shipped_at" = EXCLUDED."shipped_at"
                   ;
                   drop table order_item_TEMP;""".update.run
    } yield res
  }
}
