/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pg_catalog
package pg_stat_ssl

import doobie.enumerated.Nullability
import doobie.util.Read
import doobie.util.meta.Meta
import io.circe.Decoder
import io.circe.Encoder
import java.sql.ResultSet

case class PgStatSslViewRow(
  pid: Int,
  ssl: Boolean,
  version: String,
  cipher: String,
  bits: Int,
  clientDn: String,
  clientSerial: BigDecimal,
  issuerDn: String
)

object PgStatSslViewRow {
  implicit lazy val decoder: Decoder[PgStatSslViewRow] = Decoder.forProduct8[PgStatSslViewRow, Int, Boolean, String, String, Int, String, BigDecimal, String]("pid", "ssl", "version", "cipher", "bits", "client_dn", "client_serial", "issuer_dn")(PgStatSslViewRow.apply)(Decoder.decodeInt, Decoder.decodeBoolean, Decoder.decodeString, Decoder.decodeString, Decoder.decodeInt, Decoder.decodeString, Decoder.decodeBigDecimal, Decoder.decodeString)
  implicit lazy val encoder: Encoder[PgStatSslViewRow] = Encoder.forProduct8[PgStatSslViewRow, Int, Boolean, String, String, Int, String, BigDecimal, String]("pid", "ssl", "version", "cipher", "bits", "client_dn", "client_serial", "issuer_dn")(x => (x.pid, x.ssl, x.version, x.cipher, x.bits, x.clientDn, x.clientSerial, x.issuerDn))(Encoder.encodeInt, Encoder.encodeBoolean, Encoder.encodeString, Encoder.encodeString, Encoder.encodeInt, Encoder.encodeString, Encoder.encodeBigDecimal, Encoder.encodeString)
  implicit lazy val read: Read[PgStatSslViewRow] = new Read[PgStatSslViewRow](
    gets = List(
      (Meta.IntMeta.get, Nullability.NoNulls),
      (Meta.BooleanMeta.get, Nullability.NoNulls),
      (Meta.StringMeta.get, Nullability.NoNulls),
      (Meta.StringMeta.get, Nullability.NoNulls),
      (Meta.IntMeta.get, Nullability.NoNulls),
      (Meta.StringMeta.get, Nullability.NoNulls),
      (Meta.ScalaBigDecimalMeta.get, Nullability.NoNulls),
      (Meta.StringMeta.get, Nullability.NoNulls)
    ),
    unsafeGet = (rs: ResultSet, i: Int) => PgStatSslViewRow(
      pid = Meta.IntMeta.get.unsafeGetNonNullable(rs, i + 0),
      ssl = Meta.BooleanMeta.get.unsafeGetNonNullable(rs, i + 1),
      version = Meta.StringMeta.get.unsafeGetNonNullable(rs, i + 2),
      cipher = Meta.StringMeta.get.unsafeGetNonNullable(rs, i + 3),
      bits = Meta.IntMeta.get.unsafeGetNonNullable(rs, i + 4),
      clientDn = Meta.StringMeta.get.unsafeGetNonNullable(rs, i + 5),
      clientSerial = Meta.ScalaBigDecimalMeta.get.unsafeGetNonNullable(rs, i + 6),
      issuerDn = Meta.StringMeta.get.unsafeGetNonNullable(rs, i + 7)
    )
  )
}
