/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package information_schema
package parameters

import adventureworks.information_schema.CardinalNumber
import adventureworks.information_schema.CharacterData
import adventureworks.information_schema.SqlIdentifier
import adventureworks.information_schema.YesOrNo
import typo.dsl.SqlExpr.Field

trait ParametersViewFields[Row] {
  val specificCatalog: Field[SqlIdentifier, Row]
  val specificSchema: Field[SqlIdentifier, Row]
  val specificName: Field[SqlIdentifier, Row]
  val ordinalPosition: Field[CardinalNumber, Row]
  val parameterMode: Field[CharacterData, Row]
  val isResult: Field[YesOrNo, Row]
  val asLocator: Field[YesOrNo, Row]
  val parameterName: Field[SqlIdentifier, Row]
  val dataType: Field[CharacterData, Row]
  val characterMaximumLength: Field[CardinalNumber, Row]
  val characterOctetLength: Field[CardinalNumber, Row]
  val characterSetCatalog: Field[SqlIdentifier, Row]
  val characterSetSchema: Field[SqlIdentifier, Row]
  val characterSetName: Field[SqlIdentifier, Row]
  val collationCatalog: Field[SqlIdentifier, Row]
  val collationSchema: Field[SqlIdentifier, Row]
  val collationName: Field[SqlIdentifier, Row]
  val numericPrecision: Field[CardinalNumber, Row]
  val numericPrecisionRadix: Field[CardinalNumber, Row]
  val numericScale: Field[CardinalNumber, Row]
  val datetimePrecision: Field[CardinalNumber, Row]
  val intervalType: Field[CharacterData, Row]
  val intervalPrecision: Field[CardinalNumber, Row]
  val udtCatalog: Field[SqlIdentifier, Row]
  val udtSchema: Field[SqlIdentifier, Row]
  val udtName: Field[SqlIdentifier, Row]
  val scopeCatalog: Field[SqlIdentifier, Row]
  val scopeSchema: Field[SqlIdentifier, Row]
  val scopeName: Field[SqlIdentifier, Row]
  val maximumCardinality: Field[CardinalNumber, Row]
  val dtdIdentifier: Field[SqlIdentifier, Row]
  val parameterDefault: Field[CharacterData, Row]
}
object ParametersViewFields extends ParametersViewStructure[ParametersViewRow](None, identity, (_, x) => x)

