/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pg_catalog
package pg_auth_members

import java.sql.Connection

class PgAuthMembersRepoMock(map: scala.collection.mutable.Map[PgAuthMembersId, PgAuthMembersRow] = scala.collection.mutable.Map.empty) extends PgAuthMembersRepo {
  override def delete(compositeId: PgAuthMembersId)(implicit c: Connection): Boolean = {
    map.remove(compositeId).isDefined
  }
  override def insert(unsaved: PgAuthMembersRow)(implicit c: Connection): PgAuthMembersRow = {
    if (map.contains(unsaved.compositeId))
      sys.error(s"id ${unsaved.compositeId} already exists")
    else
      map.put(unsaved.compositeId, unsaved)
    unsaved
  }
  override def selectAll(implicit c: Connection): List[PgAuthMembersRow] = {
    map.values.toList
  }
  override def selectById(compositeId: PgAuthMembersId)(implicit c: Connection): Option[PgAuthMembersRow] = {
    map.get(compositeId)
  }
  override def update(row: PgAuthMembersRow)(implicit c: Connection): Boolean = {
    map.get(row.compositeId) match {
      case Some(`row`) => false
      case Some(_) =>
        map.put(row.compositeId, row)
        true
      case None => false
    }
  }
  override def upsert(unsaved: PgAuthMembersRow)(implicit c: Connection): PgAuthMembersRow = {
    map.put(unsaved.compositeId, unsaved)
    unsaved
  }
}
