/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package production
package productmodelillustration

import adventureworks.customtypes.Defaulted
import java.lang.Throwable
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.SelectBuilderSql
import typo.dsl.UpdateBuilder
import zio.ZIO
import zio.jdbc.SqlFragment
import zio.jdbc.SqlInterpolator
import zio.jdbc.ZConnection
import zio.stream.ZStream

object ProductmodelillustrationRepoImpl extends ProductmodelillustrationRepo {
  override def delete(compositeId: ProductmodelillustrationId): ZIO[ZConnection, Throwable, Boolean] = {
    sql"""delete from production.productmodelillustration where "productmodelid" = ??? AND "illustrationid" = ???""".update.map(_ > 0)
  }
  override def delete: DeleteBuilder[ProductmodelillustrationFields, ProductmodelillustrationRow] = {
    DeleteBuilder("production.productmodelillustration", ProductmodelillustrationFields)
  }
  override def insert(unsaved: ProductmodelillustrationRow): ZIO[ZConnection, Throwable, ProductmodelillustrationRow] = {
    sql"""insert into production.productmodelillustration("productmodelid", "illustrationid", "modifieddate")
          values (???::int4, ???::int4, ???::timestamp)
          returning "productmodelid", "illustrationid", "modifieddate"::text
       """.query(???).update.map(_ > 0)
  }
  override def insert(unsaved: ProductmodelillustrationRowUnsaved): ZIO[ZConnection, Throwable, ProductmodelillustrationRow] = {
    val fs = List(
      Some((SqlFragment(s""""productmodelid""""), sql"???::int4")),
      Some((SqlFragment(s""""illustrationid""""), sql"???::int4")),
      unsaved.modifieddate match {
        case Defaulted.UseDefault => None
        case Defaulted.Provided(value) => Some((SqlFragment(s""""modifieddate""""), sql"???::timestamp"))
      }
    ).flatten
    
    val q = if (fs.isEmpty) {
      sql"""insert into production.productmodelillustration default values
            returning "productmodelid", "illustrationid", "modifieddate"::text
         """
    } else {
      import cats.syntax.foldable.toFoldableOps
      sql"""insert into production.productmodelillustration(${fs.map { case (n, _) => n }.intercalate(sql", ")})
            values (${fs.map { case (_, f) => f }.intercalate(sql", ")})
            returning "productmodelid", "illustrationid", "modifieddate"::text
         """
    }
    q.query(???).unique
    
  }
  override def select: SelectBuilder[ProductmodelillustrationFields, ProductmodelillustrationRow] = {
    SelectBuilderSql("production.productmodelillustration", ProductmodelillustrationFields, ProductmodelillustrationRow.read)
  }
  override def selectAll: ZStream[ZConnection, Throwable, ProductmodelillustrationRow] = {
    sql"""select "productmodelid", "illustrationid", "modifieddate"::text from production.productmodelillustration""".query[ProductmodelillustrationRow].selectStream
  }
  override def selectById(compositeId: ProductmodelillustrationId): ZIO[ZConnection, Throwable, Option[ProductmodelillustrationRow]] = {
    sql"""select "productmodelid", "illustrationid", "modifieddate"::text from production.productmodelillustration where "productmodelid" = ??? AND "illustrationid" = ???""".query[ProductmodelillustrationRow].selectOne
  }
  override def update(row: ProductmodelillustrationRow): ZIO[ZConnection, Throwable, Boolean] = {
    val compositeId = row.compositeId
    sql"""update production.productmodelillustration
          set "modifieddate" = ???::timestamp
          where "productmodelid" = ??? AND "illustrationid" = ???""".update.map(_ > 0)
  }
  override def update: UpdateBuilder[ProductmodelillustrationFields, ProductmodelillustrationRow] = {
    UpdateBuilder("production.productmodelillustration", ProductmodelillustrationFields, ProductmodelillustrationRow.read)
  }
  override def upsert(unsaved: ProductmodelillustrationRow): ZIO[ZConnection, Throwable, ProductmodelillustrationRow] = {
    sql"""insert into production.productmodelillustration("productmodelid", "illustrationid", "modifieddate")
          values (
            ???::int4,
            ???::int4,
            ???::timestamp
          )
          on conflict ("productmodelid", "illustrationid")
          do update set
            "modifieddate" = EXCLUDED."modifieddate"
          returning "productmodelid", "illustrationid", "modifieddate"::text
       """.query(???).unique
  }
}
