/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package information_schema
package view_table_usage

import java.sql.Connection

trait ViewTableUsageViewRepo {
  def selectAll(implicit c: Connection): List[ViewTableUsageViewRow]
}
