/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package person
package personphone

import adventureworks.person.businessentity.BusinessentityId
import adventureworks.person.phonenumbertype.PhonenumbertypeId
import adventureworks.public.PhoneDomain
import java.time.LocalDateTime

sealed abstract class PersonphoneFieldOrIdValue[T](val name: String, val value: T)
sealed abstract class PersonphoneFieldValue[T](name: String, value: T) extends PersonphoneFieldOrIdValue(name, value)

object PersonphoneFieldValue {
  case class businessentityid(override val value: BusinessentityId) extends PersonphoneFieldOrIdValue("businessentityid", value)
  case class phonenumber(override val value: PhoneDomain) extends PersonphoneFieldOrIdValue("phonenumber", value)
  case class phonenumbertypeid(override val value: PhonenumbertypeId) extends PersonphoneFieldOrIdValue("phonenumbertypeid", value)
  case class modifieddate(override val value: LocalDateTime) extends PersonphoneFieldValue("modifieddate", value)
}
