/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pe
package ct

import adventureworks.person.contacttype.ContacttypeId
import adventureworks.public.Name
import java.time.LocalDateTime

case class CtViewRow(
  id: Option[Int],
  /** Points to [[person.contacttype.ContacttypeRow.contacttypeid]] */
  contacttypeid: Option[ContacttypeId],
  /** Points to [[person.contacttype.ContacttypeRow.name]] */
  name: Option[Name],
  /** Points to [[person.contacttype.ContacttypeRow.modifieddate]] */
  modifieddate: Option[LocalDateTime]
)


