/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.purchasing.shipmethod

import doobie.free.connection.ConnectionIO
import fs2.Stream
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder

trait ShipmethodRepo {
  def delete: DeleteBuilder[ShipmethodFields, ShipmethodRow]
  def deleteById(shipmethodid: ShipmethodId): ConnectionIO[Boolean]
  def deleteByIds(shipmethodids: Array[ShipmethodId]): ConnectionIO[Int]
  def insert(unsaved: ShipmethodRow): ConnectionIO[ShipmethodRow]
  def insert(unsaved: ShipmethodRowUnsaved): ConnectionIO[ShipmethodRow]
  def insertStreaming(unsaved: Stream[ConnectionIO, ShipmethodRow], batchSize: Int = 10000): ConnectionIO[Long]
  /* NOTE: this functionality requires PostgreSQL 16 or later! */
  def insertUnsavedStreaming(unsaved: Stream[ConnectionIO, ShipmethodRowUnsaved], batchSize: Int = 10000): ConnectionIO[Long]
  def select: SelectBuilder[ShipmethodFields, ShipmethodRow]
  def selectAll: Stream[ConnectionIO, ShipmethodRow]
  def selectById(shipmethodid: ShipmethodId): ConnectionIO[Option[ShipmethodRow]]
  def selectByIds(shipmethodids: Array[ShipmethodId]): Stream[ConnectionIO, ShipmethodRow]
  def selectByIdsTracked(shipmethodids: Array[ShipmethodId]): ConnectionIO[Map[ShipmethodId, ShipmethodRow]]
  def update: UpdateBuilder[ShipmethodFields, ShipmethodRow]
  def update(row: ShipmethodRow): ConnectionIO[Boolean]
  def upsert(unsaved: ShipmethodRow): ConnectionIO[ShipmethodRow]
  def upsertBatch(unsaved: List[ShipmethodRow]): Stream[ConnectionIO, ShipmethodRow]
  /* NOTE: this functionality is not safe if you use auto-commit mode! it runs 3 SQL statements */
  def upsertStreaming(unsaved: Stream[ConnectionIO, ShipmethodRow], batchSize: Int = 10000): ConnectionIO[Int]
}
