/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pe
package a

import adventureworks.person.address.AddressId
import adventureworks.person.stateprovince.StateprovinceId
import doobie.Get
import doobie.Read
import doobie.enumerated.Nullability
import doobie.free.connection.ConnectionIO
import doobie.syntax.string.toSqlInterpolator
import doobie.util.fragments
import fs2.Stream
import java.sql.ResultSet
import java.time.LocalDateTime
import java.util.UUID

object AViewRepoImpl extends AViewRepo {
  override def selectAll: Stream[ConnectionIO, AViewRow] = {
    sql"""select "id", addressid, addressline1, addressline2, city, stateprovinceid, postalcode, spatiallocation, rowguid, modifieddate from pe."a"""".query[AViewRow].stream
  }
  override def selectByFieldValues(fieldValues: List[AViewFieldOrIdValue[_]]): Stream[ConnectionIO, AViewRow] = {
    val where = fragments.whereAnd(
      fieldValues.map {
        case AViewFieldValue.id(value) => fr""""id" = $value"""
        case AViewFieldValue.addressid(value) => fr"addressid = $value"
        case AViewFieldValue.addressline1(value) => fr"addressline1 = $value"
        case AViewFieldValue.addressline2(value) => fr"addressline2 = $value"
        case AViewFieldValue.city(value) => fr"city = $value"
        case AViewFieldValue.stateprovinceid(value) => fr"stateprovinceid = $value"
        case AViewFieldValue.postalcode(value) => fr"postalcode = $value"
        case AViewFieldValue.spatiallocation(value) => fr"spatiallocation = $value"
        case AViewFieldValue.rowguid(value) => fr"rowguid = $value"
        case AViewFieldValue.modifieddate(value) => fr"modifieddate = $value"
      } :_*
    )
    sql"""select * from pe."a" $where""".query[AViewRow].stream
  
  }
  implicit val read: Read[AViewRow] =
    new Read[AViewRow](
      gets = List(
        (Get[Int], Nullability.Nullable),
        (Get[AddressId], Nullability.Nullable),
        (Get[/* max 60 chars */ String], Nullability.Nullable),
        (Get[/* max 60 chars */ String], Nullability.Nullable),
        (Get[/* max 30 chars */ String], Nullability.Nullable),
        (Get[StateprovinceId], Nullability.Nullable),
        (Get[/* max 15 chars */ String], Nullability.Nullable),
        (Get[Byte], Nullability.Nullable),
        (Get[UUID], Nullability.Nullable),
        (Get[LocalDateTime], Nullability.Nullable)
      ),
      unsafeGet = (rs: ResultSet, i: Int) => AViewRow(
        id = Get[Int].unsafeGetNullable(rs, i + 0),
        addressid = Get[AddressId].unsafeGetNullable(rs, i + 1),
        addressline1 = Get[/* max 60 chars */ String].unsafeGetNullable(rs, i + 2),
        addressline2 = Get[/* max 60 chars */ String].unsafeGetNullable(rs, i + 3),
        city = Get[/* max 30 chars */ String].unsafeGetNullable(rs, i + 4),
        stateprovinceid = Get[StateprovinceId].unsafeGetNullable(rs, i + 5),
        postalcode = Get[/* max 15 chars */ String].unsafeGetNullable(rs, i + 6),
        spatiallocation = Get[Byte].unsafeGetNullable(rs, i + 7),
        rowguid = Get[UUID].unsafeGetNullable(rs, i + 8),
        modifieddate = Get[LocalDateTime].unsafeGetNullable(rs, i + 9)
      )
    )
  

}
