/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pg_catalog
package pg_amop

import adventureworks.customtypes.TypoShort
import java.lang.Throwable
import typo.dsl.DeleteBuilder
import typo.dsl.SelectBuilder
import typo.dsl.UpdateBuilder
import zio.ZIO
import zio.jdbc.ZConnection
import zio.stream.ZStream

class PgAmopRepoMock(map: scala.collection.mutable.Map[PgAmopId, PgAmopRow] = scala.collection.mutable.Map.empty) extends PgAmopRepo {
  override def delete(oid: PgAmopId): ZIO[ZConnection, Throwable, Boolean] = {
    ???
  }
  override def delete: DeleteBuilder[PgAmopFields, PgAmopRow] = {
    ???
  }
  override def insert(unsaved: PgAmopRow): ZIO[ZConnection, Throwable, PgAmopRow] = {
    ???
  }
  override def select: SelectBuilder[PgAmopFields, PgAmopRow] = {
    ???
  }
  override def selectAll: ZStream[ZConnection, Throwable, PgAmopRow] = {
    ???
  }
  override def selectById(oid: PgAmopId): ZIO[ZConnection, Throwable, Option[PgAmopRow]] = {
    ???
  }
  override def selectByIds(oids: Array[PgAmopId]): ZStream[ZConnection, Throwable, PgAmopRow] = {
    ???
  }
  override def selectByUnique(amopfamily: /* oid */ Long, amoplefttype: /* oid */ Long, amoprighttype: /* oid */ Long, amopstrategy: TypoShort): ZIO[ZConnection, Throwable, Option[PgAmopRow]] = {
    ???
  }
  override def selectByUnique(amopopr: /* oid */ Long, amoppurpose: String, amopfamily: /* oid */ Long): ZIO[ZConnection, Throwable, Option[PgAmopRow]] = {
    ???
  }
  override def update(row: PgAmopRow): ZIO[ZConnection, Throwable, Boolean] = {
    ???
  }
  override def update: UpdateBuilder[PgAmopFields, PgAmopRow] = {
    ???
  }
  override def upsert(unsaved: PgAmopRow): ZIO[ZConnection, Throwable, PgAmopRow] = {
    ???
  }
}
