/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pu
package v

import typo.dsl.SelectBuilder
import typo.dsl.SelectBuilderSql
import zio.jdbc.ZConnection
import zio.jdbc.sqlInterpolator
import zio.stream.ZStream

class VViewRepoImpl extends VViewRepo {
  override def select: SelectBuilder[VViewFields, VViewRow] = {
    SelectBuilderSql("pu.v", VViewFields.structure, VViewRow.jdbcDecoder)
  }
  override def selectAll: ZStream[ZConnection, Throwable, VViewRow] = {
    sql"""select "id", "businessentityid", "accountnumber", "name", "creditrating", "preferredvendorstatus", "activeflag", "purchasingwebserviceurl", "modifieddate"::text from pu.v""".query(using VViewRow.jdbcDecoder).selectStream()
  }
}
