/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pr
package pmi

import adventureworks.production.illustration.IllustrationId
import adventureworks.production.productmodel.ProductmodelId
import java.time.LocalDateTime
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.Json
import play.api.libs.json.OFormat
import scala.util.Try

case class PmiRow(
  /** Points to [[production.productmodelillustration.ProductmodelillustrationRow.productmodelid]] */
  productmodelid: Option[ProductmodelId],
  /** Points to [[production.productmodelillustration.ProductmodelillustrationRow.illustrationid]] */
  illustrationid: Option[IllustrationId],
  /** Points to [[production.productmodelillustration.ProductmodelillustrationRow.modifieddate]] */
  modifieddate: Option[LocalDateTime]
)

object PmiRow {
  implicit val oFormat: OFormat[PmiRow] = new OFormat[PmiRow]{
    override def writes(o: PmiRow): JsObject =
      Json.obj(
        "productmodelid" -> o.productmodelid,
        "illustrationid" -> o.illustrationid,
        "modifieddate" -> o.modifieddate
      )
  
    override def reads(json: JsValue): JsResult[PmiRow] = {
      JsResult.fromTry(
        Try(
          PmiRow(
            productmodelid = json.\("productmodelid").toOption.map(_.as[ProductmodelId]),
            illustrationid = json.\("illustrationid").toOption.map(_.as[IllustrationId]),
            modifieddate = json.\("modifieddate").toOption.map(_.as[LocalDateTime])
          )
        )
      )
    }
  }
}
