/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pr
package wr

import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.production.location.LocationId
import adventureworks.production.workorder.WorkorderId
import typo.dsl.SqlExpr.Field

trait WrViewFields[Row] {
  val id: Field[Int, Row]
  val workorderid: Field[WorkorderId, Row]
  val productid: Field[Int, Row]
  val operationsequence: Field[Int, Row]
  val locationid: Field[LocationId, Row]
  val scheduledstartdate: Field[TypoLocalDateTime, Row]
  val scheduledenddate: Field[TypoLocalDateTime, Row]
  val actualstartdate: Field[TypoLocalDateTime, Row]
  val actualenddate: Field[TypoLocalDateTime, Row]
  val actualresourcehrs: Field[BigDecimal, Row]
  val plannedcost: Field[BigDecimal, Row]
  val actualcost: Field[BigDecimal, Row]
  val modifieddate: Field[TypoLocalDateTime, Row]
}
object WrViewFields extends WrViewStructure[WrViewRow](None, identity, (_, x) => x)

