/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pr
package p

import adventureworks.production.product.ProductId
import adventureworks.production.productmodel.ProductmodelId
import adventureworks.production.productsubcategory.ProductsubcategoryId
import adventureworks.production.unitmeasure.UnitmeasureId
import java.time.LocalDateTime
import java.util.UUID

sealed abstract class PFieldOrIdValue[T](val name: String, val value: T)
sealed abstract class PFieldValue[T](name: String, value: T) extends PFieldOrIdValue(name, value)

object PFieldValue {
  case class id(override val value: Option[Int]) extends PFieldValue("id", value)
  case class productid(override val value: Option[ProductId]) extends PFieldValue("productid", value)
  case class name(override val value: Option[String]) extends PFieldValue("name", value)
  case class productnumber(override val value: Option[String]) extends PFieldValue("productnumber", value)
  case class makeflag(override val value: Boolean) extends PFieldValue("makeflag", value)
  case class finishedgoodsflag(override val value: Boolean) extends PFieldValue("finishedgoodsflag", value)
  case class color(override val value: Option[String]) extends PFieldValue("color", value)
  case class safetystocklevel(override val value: Option[Int]) extends PFieldValue("safetystocklevel", value)
  case class reorderpoint(override val value: Option[Int]) extends PFieldValue("reorderpoint", value)
  case class standardcost(override val value: Option[BigDecimal]) extends PFieldValue("standardcost", value)
  case class listprice(override val value: Option[BigDecimal]) extends PFieldValue("listprice", value)
  case class size(override val value: Option[String]) extends PFieldValue("size", value)
  case class sizeunitmeasurecode(override val value: Option[UnitmeasureId]) extends PFieldValue("sizeunitmeasurecode", value)
  case class weightunitmeasurecode(override val value: Option[UnitmeasureId]) extends PFieldValue("weightunitmeasurecode", value)
  case class weight(override val value: Option[BigDecimal]) extends PFieldValue("weight", value)
  case class daystomanufacture(override val value: Option[Int]) extends PFieldValue("daystomanufacture", value)
  case class productline(override val value: Option[/* bpchar */ String]) extends PFieldValue("productline", value)
  case class `class`(override val value: Option[/* bpchar */ String]) extends PFieldValue("class", value)
  case class style(override val value: Option[/* bpchar */ String]) extends PFieldValue("style", value)
  case class productsubcategoryid(override val value: Option[ProductsubcategoryId]) extends PFieldValue("productsubcategoryid", value)
  case class productmodelid(override val value: Option[ProductmodelId]) extends PFieldValue("productmodelid", value)
  case class sellstartdate(override val value: Option[LocalDateTime]) extends PFieldValue("sellstartdate", value)
  case class sellenddate(override val value: Option[LocalDateTime]) extends PFieldValue("sellenddate", value)
  case class discontinueddate(override val value: Option[LocalDateTime]) extends PFieldValue("discontinueddate", value)
  case class rowguid(override val value: Option[UUID]) extends PFieldValue("rowguid", value)
  case class modifieddate(override val value: Option[LocalDateTime]) extends PFieldValue("modifieddate", value)
}
