/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sales.vindividualcustomer

import java.sql.Connection
import typo.dsl.SelectBuilder

trait VindividualcustomerViewRepo {
  def select: SelectBuilder[VindividualcustomerViewFields, VindividualcustomerViewRow]
  def selectAll(implicit c: Connection): List[VindividualcustomerViewRow]
}
