/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.sa.s;

import java.sql.Connection;
import typo.dsl.SelectBuilder;

trait SViewRepo {
  def select: SelectBuilder[SViewFields, SViewRow]
  def selectAll(implicit c: Connection): List[SViewRow]
}