/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package information_schema
package routine_column_usage

import zio.json.DeriveJsonDecoder
import zio.json.DeriveJsonEncoder
import zio.json.JsonDecoder

case class RoutineColumnUsageViewRow(
  specificCatalog: /* nullability unknown */ Option[String],
  specificSchema: /* nullability unknown */ Option[String],
  specificName: /* nullability unknown */ Option[String],
  routineCatalog: /* nullability unknown */ Option[String],
  routineSchema: /* nullability unknown */ Option[String],
  routineName: /* nullability unknown */ Option[String],
  tableCatalog: /* nullability unknown */ Option[String],
  tableSchema: /* nullability unknown */ Option[String],
  tableName: /* nullability unknown */ Option[String],
  columnName: /* nullability unknown */ Option[String]
)

object RoutineColumnUsageViewRow {
  implicit lazy val decoder: JsonDecoder[RoutineColumnUsageViewRow] = DeriveJsonDecoder.gen[RoutineColumnUsageViewRow]
  implicit lazy val decoder: JsonDecoder[RoutineColumnUsageViewRow] = DeriveJsonEncoder.gen[RoutineColumnUsageViewRow]
}
