/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.production.productcategory;



/** Type for the primary key of table `production.productcategory` */
public record ProductcategoryId(Integer value) {
  
}