/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package purchasing
package vvendorwithaddresses

import adventureworks.person.businessentity.BusinessentityId
import adventureworks.public.Name

sealed abstract class VvendorwithaddressesViewFieldOrIdValue[T](val name: String, val value: T)
sealed abstract class VvendorwithaddressesViewFieldValue[T](name: String, value: T) extends VvendorwithaddressesViewFieldOrIdValue(name, value)

object VvendorwithaddressesViewFieldValue {
  case class businessentityid(override val value: Option[BusinessentityId]) extends VvendorwithaddressesViewFieldValue("businessentityid", value)
  case class name(override val value: Option[Name]) extends VvendorwithaddressesViewFieldValue("name", value)
  case class addresstype(override val value: Option[Name]) extends VvendorwithaddressesViewFieldValue("addresstype", value)
  case class addressline1(override val value: Option[/* max 60 chars */ String]) extends VvendorwithaddressesViewFieldValue("addressline1", value)
  case class addressline2(override val value: Option[/* max 60 chars */ String]) extends VvendorwithaddressesViewFieldValue("addressline2", value)
  case class city(override val value: Option[/* max 30 chars */ String]) extends VvendorwithaddressesViewFieldValue("city", value)
  case class stateprovincename(override val value: Option[Name]) extends VvendorwithaddressesViewFieldValue("stateprovincename", value)
  case class postalcode(override val value: Option[/* max 15 chars */ String]) extends VvendorwithaddressesViewFieldValue("postalcode", value)
  case class countryregionname(override val value: Option[Name]) extends VvendorwithaddressesViewFieldValue("countryregionname", value)
}
