/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.production.productlistpricehistory;

import adventureworks.customtypes.TypoLocalDateTime;
import adventureworks.production.product.ProductId;

/** Type for the composite primary key of table `production.productlistpricehistory` */
public record ProductlistpricehistoryId(ProductId productid, TypoLocalDateTime startdate) {
  
}