/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks.public_.users;

import adventureworks.customtypes.Defaulted;
import adventureworks.customtypes.TypoInstant;
import adventureworks.customtypes.TypoUnknownCitext;
import java.util.Optional;

/** This class corresponds to a row in table `public.users` which has not been persisted yet */
public record UsersRowUnsaved(
  UsersId userId,
  String name,
  Optional<String> lastName,
  TypoUnknownCitext email,
  String password,
  Optional<TypoInstant> verifiedOn,
  /** Default: now() */
  Defaulted<TypoInstant> createdAt
) {
  public UsersRow toRow(java.util.function.Supplier<TypoInstant> createdAtDefault) {
    return new UsersRow(userId, name, lastName, email, password, createdAt.getOrElse(createdAtDefault), verifiedOn);
  };
}