/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package sa
package sod

import doobie.free.connection.ConnectionIO
import fs2.Stream

trait SodViewRepo {
  def selectAll: Stream[ConnectionIO, SodViewRow]
  def selectByFieldValues(fieldValues: List[SodViewFieldOrIdValue[_]]): Stream[ConnectionIO, SodViewRow]
}
