/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package sa
package sohsr

import adventureworks.sales.salesorderheader.SalesorderheaderId
import adventureworks.sales.salesreason.SalesreasonId
import anorm.NamedParameter
import anorm.ParameterValue
import anorm.RowParser
import anorm.SqlStringInterpolation
import anorm.Success
import java.sql.Connection
import java.time.LocalDateTime

object SohsrViewRepoImpl extends SohsrViewRepo {
  override def selectAll(implicit c: Connection): List[SohsrViewRow] = {
    SQL"""select salesorderid, salesreasonid, modifieddate
          from sa.sohsr
       """.as(rowParser.*)
  }
  override def selectByFieldValues(fieldValues: List[SohsrViewFieldOrIdValue[_]])(implicit c: Connection): List[SohsrViewRow] = {
    fieldValues match {
      case Nil => selectAll
      case nonEmpty =>
        val namedParams = nonEmpty.map{
          case SohsrViewFieldValue.salesorderid(value) => NamedParameter("salesorderid", ParameterValue.from(value))
          case SohsrViewFieldValue.salesreasonid(value) => NamedParameter("salesreasonid", ParameterValue.from(value))
          case SohsrViewFieldValue.modifieddate(value) => NamedParameter("modifieddate", ParameterValue.from(value))
        }
        val quote = '"'.toString
        val q = s"""select salesorderid, salesreasonid, modifieddate
                    from sa.sohsr
                    where ${namedParams.map(x => s"$quote${x.name}$quote = {${x.name}}").mkString(" AND ")}
                 """
        // this line is here to include an extension method which is only needed for scala 3. no import is emitted for `SQL` to avoid warning for scala 2
        import anorm._
        SQL(q)
          .on(namedParams: _*)
          .as(rowParser.*)
    }
  
  }
  val rowParser: RowParser[SohsrViewRow] =
    RowParser[SohsrViewRow] { row =>
      Success(
        SohsrViewRow(
          salesorderid = row[Option[SalesorderheaderId]]("salesorderid"),
          salesreasonid = row[Option[SalesreasonId]]("salesreasonid"),
          modifieddate = row[Option[LocalDateTime]]("modifieddate")
        )
      )
    }
}
