/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pg_catalog
package pg_constraint

import doobie.Meta
import io.circe.Decoder
import io.circe.Encoder

/** Type for the primary key of table `pg_catalog.pg_constraint` */
case class PgConstraintId(value: /* oid */ Long) extends AnyVal
object PgConstraintId {
  implicit val ordering: Ordering[PgConstraintId] = Ordering.by(_.value)
  implicit val encoder: Encoder[PgConstraintId] =
    Encoder[/* oid */ Long].contramap(_.value)
  implicit val decoder: Decoder[PgConstraintId] =
    Decoder[/* oid */ Long].map(PgConstraintId(_))
  implicit val meta: Meta[PgConstraintId] = Meta[/* oid */ Long].imap(PgConstraintId.apply)(_.value)
  implicit val metaArray: Meta[Array[PgConstraintId]] = Meta[Array[/* oid */ Long]].imap(_.map(PgConstraintId.apply))(_.map(_.value))
}
