/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pg_catalog
package pg_authid

import anorm.SqlStringInterpolation
import java.sql.Connection

object PgAuthidRepoImpl extends PgAuthidRepo {
  override def delete(oid: PgAuthidId)(implicit c: Connection): Boolean = {
    SQL"delete from pg_catalog.pg_authid where oid = $oid".executeUpdate() > 0
  }
  override def insert(unsaved: PgAuthidRow)(implicit c: Connection): PgAuthidRow = {
    SQL"""insert into pg_catalog.pg_authid(oid, rolname, rolsuper, rolinherit, rolcreaterole, rolcreatedb, rolcanlogin, rolreplication, rolbypassrls, rolconnlimit, rolpassword, rolvaliduntil)
          values (${unsaved.oid}::oid, ${unsaved.rolname}::name, ${unsaved.rolsuper}, ${unsaved.rolinherit}, ${unsaved.rolcreaterole}, ${unsaved.rolcreatedb}, ${unsaved.rolcanlogin}, ${unsaved.rolreplication}, ${unsaved.rolbypassrls}, ${unsaved.rolconnlimit}::int4, ${unsaved.rolpassword}, ${unsaved.rolvaliduntil}::timestamptz)
          returning oid, rolname, rolsuper, rolinherit, rolcreaterole, rolcreatedb, rolcanlogin, rolreplication, rolbypassrls, rolconnlimit, rolpassword, rolvaliduntil
       """
      .executeInsert(PgAuthidRow.rowParser(1).single)
  
  }
  override def selectAll(implicit c: Connection): List[PgAuthidRow] = {
    SQL"""select oid, rolname, rolsuper, rolinherit, rolcreaterole, rolcreatedb, rolcanlogin, rolreplication, rolbypassrls, rolconnlimit, rolpassword, rolvaliduntil
          from pg_catalog.pg_authid
       """.as(PgAuthidRow.rowParser(1).*)
  }
  override def selectById(oid: PgAuthidId)(implicit c: Connection): Option[PgAuthidRow] = {
    SQL"""select oid, rolname, rolsuper, rolinherit, rolcreaterole, rolcreatedb, rolcanlogin, rolreplication, rolbypassrls, rolconnlimit, rolpassword, rolvaliduntil
          from pg_catalog.pg_authid
          where oid = $oid
       """.as(PgAuthidRow.rowParser(1).singleOpt)
  }
  override def selectByIds(oids: Array[PgAuthidId])(implicit c: Connection): List[PgAuthidRow] = {
    SQL"""select oid, rolname, rolsuper, rolinherit, rolcreaterole, rolcreatedb, rolcanlogin, rolreplication, rolbypassrls, rolconnlimit, rolpassword, rolvaliduntil
          from pg_catalog.pg_authid
          where oid = ANY($oids)
       """.as(PgAuthidRow.rowParser(1).*)
  
  }
  override def update(row: PgAuthidRow)(implicit c: Connection): Boolean = {
    val oid = row.oid
    SQL"""update pg_catalog.pg_authid
          set rolname = ${row.rolname}::name,
              rolsuper = ${row.rolsuper},
              rolinherit = ${row.rolinherit},
              rolcreaterole = ${row.rolcreaterole},
              rolcreatedb = ${row.rolcreatedb},
              rolcanlogin = ${row.rolcanlogin},
              rolreplication = ${row.rolreplication},
              rolbypassrls = ${row.rolbypassrls},
              rolconnlimit = ${row.rolconnlimit}::int4,
              rolpassword = ${row.rolpassword},
              rolvaliduntil = ${row.rolvaliduntil}::timestamptz
          where oid = $oid
       """.executeUpdate() > 0
  }
  override def upsert(unsaved: PgAuthidRow)(implicit c: Connection): PgAuthidRow = {
    SQL"""insert into pg_catalog.pg_authid(oid, rolname, rolsuper, rolinherit, rolcreaterole, rolcreatedb, rolcanlogin, rolreplication, rolbypassrls, rolconnlimit, rolpassword, rolvaliduntil)
          values (
            ${unsaved.oid}::oid,
            ${unsaved.rolname}::name,
            ${unsaved.rolsuper},
            ${unsaved.rolinherit},
            ${unsaved.rolcreaterole},
            ${unsaved.rolcreatedb},
            ${unsaved.rolcanlogin},
            ${unsaved.rolreplication},
            ${unsaved.rolbypassrls},
            ${unsaved.rolconnlimit}::int4,
            ${unsaved.rolpassword},
            ${unsaved.rolvaliduntil}::timestamptz
          )
          on conflict (oid)
          do update set
            rolname = EXCLUDED.rolname,
            rolsuper = EXCLUDED.rolsuper,
            rolinherit = EXCLUDED.rolinherit,
            rolcreaterole = EXCLUDED.rolcreaterole,
            rolcreatedb = EXCLUDED.rolcreatedb,
            rolcanlogin = EXCLUDED.rolcanlogin,
            rolreplication = EXCLUDED.rolreplication,
            rolbypassrls = EXCLUDED.rolbypassrls,
            rolconnlimit = EXCLUDED.rolconnlimit,
            rolpassword = EXCLUDED.rolpassword,
            rolvaliduntil = EXCLUDED.rolvaliduntil
          returning oid, rolname, rolsuper, rolinherit, rolcreaterole, rolcreatedb, rolcanlogin, rolreplication, rolbypassrls, rolconnlimit, rolpassword, rolvaliduntil
       """
      .executeInsert(PgAuthidRow.rowParser(1).single)
  
  }
}
