/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package frontpage
package product

import adventureworks.customtypes.TypoUUID
import typo.dsl.Bijection
import typo.dsl.PGType
import zio.jdbc.JdbcDecoder
import zio.jdbc.JdbcEncoder
import zio.jdbc.SqlFragment.Setter
import zio.json.JsonDecoder
import zio.json.JsonEncoder

/** Type for the primary key of table `frontpage.product` */
case class ProductId(value: TypoUUID) extends AnyVal
object ProductId {
  implicit lazy val arrayJdbcDecoder: JdbcDecoder[Array[ProductId]] = JdbcDecoder[Array[TypoUUID]].map(_.map(ProductId.apply))
  implicit lazy val arrayJdbcEncoder: JdbcEncoder[Array[ProductId]] = JdbcEncoder[Array[TypoUUID]].contramap(_.map(_.value))
  implicit lazy val arraySetter: Setter[Array[ProductId]] = TypoUUID.arraySetter.contramap(_.map(_.value))
  implicit lazy val bijection: Bijection[ProductId, TypoUUID] = Bijection[ProductId, TypoUUID](_.value)(ProductId.apply)
  implicit lazy val jdbcDecoder: JdbcDecoder[ProductId] = TypoUUID.jdbcDecoder.map(ProductId.apply)
  implicit lazy val jdbcEncoder: JdbcEncoder[ProductId] = TypoUUID.jdbcEncoder.contramap(_.value)
  implicit lazy val jsonDecoder: JsonDecoder[ProductId] = TypoUUID.jsonDecoder.map(ProductId.apply)
  implicit lazy val jsonEncoder: JsonEncoder[ProductId] = TypoUUID.jsonEncoder.contramap(_.value)
  implicit def ordering(implicit O0: Ordering[TypoUUID]): Ordering[ProductId] = Ordering.by(_.value)
  implicit lazy val pgType: PGType[ProductId] = TypoUUID.pgType.as
  implicit lazy val setter: Setter[ProductId] = TypoUUID.setter.contramap(_.value)
  implicit lazy val text: Text[ProductId] = new Text[ProductId] {
    override def unsafeEncode(v: ProductId, sb: StringBuilder) = TypoUUID.text.unsafeEncode(v.value, sb)
    override def unsafeArrayEncode(v: ProductId, sb: StringBuilder) = TypoUUID.text.unsafeArrayEncode(v.value, sb)
  }
}
