/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pr
package psc

import adventureworks.customtypes.TypoLocalDateTime
import adventureworks.production.productcategory.ProductcategoryId
import adventureworks.production.productsubcategory.ProductsubcategoryId
import adventureworks.public.Name
import anorm.Column
import anorm.RowParser
import anorm.Success
import java.util.UUID
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.OWrites
import play.api.libs.json.Reads
import play.api.libs.json.Writes
import scala.collection.immutable.ListMap
import scala.util.Try

case class PscViewRow(
  id: Int,
  /** Points to [[production.productsubcategory.ProductsubcategoryRow.productsubcategoryid]] */
  productsubcategoryid: ProductsubcategoryId,
  /** Points to [[production.productsubcategory.ProductsubcategoryRow.productcategoryid]] */
  productcategoryid: ProductcategoryId,
  /** Points to [[production.productsubcategory.ProductsubcategoryRow.name]] */
  name: Name,
  /** Points to [[production.productsubcategory.ProductsubcategoryRow.rowguid]] */
  rowguid: UUID,
  /** Points to [[production.productsubcategory.ProductsubcategoryRow.modifieddate]] */
  modifieddate: TypoLocalDateTime
)

object PscViewRow {
  implicit lazy val reads: Reads[PscViewRow] = Reads[PscViewRow](json => JsResult.fromTry(
      Try(
        PscViewRow(
          id = json.\("id").as(Reads.IntReads),
          productsubcategoryid = json.\("productsubcategoryid").as(ProductsubcategoryId.reads),
          productcategoryid = json.\("productcategoryid").as(ProductcategoryId.reads),
          name = json.\("name").as(Name.reads),
          rowguid = json.\("rowguid").as(Reads.uuidReads),
          modifieddate = json.\("modifieddate").as(TypoLocalDateTime.reads)
        )
      )
    ),
  )
  def rowParser(idx: Int): RowParser[PscViewRow] = RowParser[PscViewRow] { row =>
    Success(
      PscViewRow(
        id = row(idx + 0)(Column.columnToInt),
        productsubcategoryid = row(idx + 1)(ProductsubcategoryId.column),
        productcategoryid = row(idx + 2)(ProductcategoryId.column),
        name = row(idx + 3)(Name.column),
        rowguid = row(idx + 4)(Column.columnToUUID),
        modifieddate = row(idx + 5)(TypoLocalDateTime.column)
      )
    )
  }
  implicit lazy val writes: OWrites[PscViewRow] = OWrites[PscViewRow](o =>
    new JsObject(ListMap[String, JsValue](
      "id" -> Writes.IntWrites.writes(o.id),
      "productsubcategoryid" -> ProductsubcategoryId.writes.writes(o.productsubcategoryid),
      "productcategoryid" -> ProductcategoryId.writes.writes(o.productcategoryid),
      "name" -> Name.writes.writes(o.name),
      "rowguid" -> Writes.UuidWrites.writes(o.rowguid),
      "modifieddate" -> TypoLocalDateTime.writes.writes(o.modifieddate)
    ))
  )
}
