/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package pe
package ct

import adventureworks.TypoLocalDateTime
import adventureworks.person.contacttype.ContacttypeId
import adventureworks.public.Name
import doobie.enumerated.Nullability
import doobie.util.Read
import doobie.util.meta.Meta
import io.circe.Decoder
import io.circe.Encoder
import java.sql.ResultSet

case class CtViewRow(
  id: Option[Int],
  /** Points to [[person.contacttype.ContacttypeRow.contacttypeid]] */
  contacttypeid: Option[ContacttypeId],
  /** Points to [[person.contacttype.ContacttypeRow.name]] */
  name: Option[Name],
  /** Points to [[person.contacttype.ContacttypeRow.modifieddate]] */
  modifieddate: Option[TypoLocalDateTime]
)

object CtViewRow {
  implicit lazy val decoder: Decoder[CtViewRow] = Decoder.forProduct4[CtViewRow, Option[Int], Option[ContacttypeId], Option[Name], Option[TypoLocalDateTime]]("id", "contacttypeid", "name", "modifieddate")(CtViewRow.apply)(Decoder.decodeOption(Decoder.decodeInt), Decoder.decodeOption(ContacttypeId.decoder), Decoder.decodeOption(Name.decoder), Decoder.decodeOption(TypoLocalDateTime.decoder))
  implicit lazy val encoder: Encoder[CtViewRow] = Encoder.forProduct4[CtViewRow, Option[Int], Option[ContacttypeId], Option[Name], Option[TypoLocalDateTime]]("id", "contacttypeid", "name", "modifieddate")(x => (x.id, x.contacttypeid, x.name, x.modifieddate))(Encoder.encodeOption(Encoder.encodeInt), Encoder.encodeOption(ContacttypeId.encoder), Encoder.encodeOption(Name.encoder), Encoder.encodeOption(TypoLocalDateTime.encoder))
  implicit lazy val read: Read[CtViewRow] = new Read[CtViewRow](
    gets = List(
      (Meta.IntMeta.get, Nullability.Nullable),
      (ContacttypeId.get, Nullability.Nullable),
      (Name.get, Nullability.Nullable),
      (TypoLocalDateTime.get, Nullability.Nullable)
    ),
    unsafeGet = (rs: ResultSet, i: Int) => CtViewRow(
      id = Meta.IntMeta.get.unsafeGetNullable(rs, i + 0),
      contacttypeid = ContacttypeId.get.unsafeGetNullable(rs, i + 1),
      name = Name.get.unsafeGetNullable(rs, i + 2),
      modifieddate = TypoLocalDateTime.get.unsafeGetNullable(rs, i + 3)
    )
  )
}
