/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package frontpage
package department

import adventureworks.customtypes.TypoUUID
import doobie.postgres.Text
import doobie.util.Get
import doobie.util.Put
import io.circe.Decoder
import io.circe.Encoder
import typo.dsl.Bijection

/** Type for the primary key of table `frontpage.department` */
case class DepartmentId(value: TypoUUID) extends AnyVal
object DepartmentId {
  implicit lazy val arrayGet: Get[Array[DepartmentId]] = TypoUUID.arrayGet.map(_.map(DepartmentId.apply))
  implicit lazy val arrayPut: Put[Array[DepartmentId]] = TypoUUID.arrayPut.contramap(_.map(_.value))
  implicit lazy val bijection: Bijection[DepartmentId, TypoUUID] = Bijection[DepartmentId, TypoUUID](_.value)(DepartmentId.apply)
  implicit lazy val decoder: Decoder[DepartmentId] = TypoUUID.decoder.map(DepartmentId.apply)
  implicit lazy val encoder: Encoder[DepartmentId] = TypoUUID.encoder.contramap(_.value)
  implicit lazy val get: Get[DepartmentId] = TypoUUID.get.map(DepartmentId.apply)
  implicit def ordering(implicit O0: Ordering[TypoUUID]): Ordering[DepartmentId] = Ordering.by(_.value)
  implicit lazy val put: Put[DepartmentId] = TypoUUID.put.contramap(_.value)
  implicit lazy val text: Text[DepartmentId] = new Text[DepartmentId] {
    override def unsafeEncode(v: DepartmentId, sb: StringBuilder) = TypoUUID.text.unsafeEncode(v.value, sb)
    override def unsafeArrayEncode(v: DepartmentId, sb: StringBuilder) = TypoUUID.text.unsafeArrayEncode(v.value, sb)
  }
}
