/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package production
package vproductanddescription

import doobie.free.connection.ConnectionIO
import doobie.syntax.string.toSqlInterpolator
import fs2.Stream
import typo.dsl.SelectBuilder
import typo.dsl.SelectBuilderSql

object VproductanddescriptionMVRepoImpl extends VproductanddescriptionMVRepo {
  override def select: SelectBuilder[VproductanddescriptionMVFields, VproductanddescriptionMVRow] = {
    SelectBuilderSql("production.vproductanddescription", VproductanddescriptionMVFields, VproductanddescriptionMVRow.read)
  }
  override def selectAll: Stream[ConnectionIO, VproductanddescriptionMVRow] = {
    sql"""select "productid", "name", "productmodel", "cultureid", "description" from production.vproductanddescription""".query(VproductanddescriptionMVRow.read).stream
  }
}
