/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package sales
package vsalespersonsalesbyfiscalyearsdata

import java.sql.Connection

trait VsalespersonsalesbyfiscalyearsdataRepo {
  def selectAll(implicit c: Connection): List[VsalespersonsalesbyfiscalyearsdataRow]
  def selectByFieldValues(fieldValues: List[VsalespersonsalesbyfiscalyearsdataFieldOrIdValue[_]])(implicit c: Connection): List[VsalespersonsalesbyfiscalyearsdataRow]
}
