/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package sales
package creditcard

import anorm.Column
import anorm.ParameterMetaData
import anorm.ToStatement
import play.api.libs.json.Reads
import play.api.libs.json.Writes

/** Type for the primary key of table `sales.creditcard` */
case class CreditcardId(value: Int) extends AnyVal
object CreditcardId {
  implicit val arrayToStatement: ToStatement[Array[CreditcardId]] = implicitly[ToStatement[Array[Int]]].contramap(_.map(_.value))
  implicit val column: Column[CreditcardId] = implicitly[Column[Int]].map(CreditcardId.apply)
  implicit val ordering: Ordering[CreditcardId] = Ordering.by(_.value)
  implicit val parameterMetadata: ParameterMetaData[CreditcardId] = new ParameterMetaData[CreditcardId] {
    override def sqlType: String = implicitly[ParameterMetaData[Int]].sqlType
    override def jdbcType: Int = implicitly[ParameterMetaData[Int]].jdbcType
  }
  implicit val reads: Reads[CreditcardId] = Reads.IntReads.map(CreditcardId.apply)
  implicit val toStatement: ToStatement[CreditcardId] = implicitly[ToStatement[Int]].contramap(_.value)
  implicit val writes: Writes[CreditcardId] = Writes.IntWrites.contramap(_.value)
}
