/**
 * File has been automatically generated by `typo`.
 *
 * IF YOU CHANGE THIS FILE YOUR CHANGES WILL BE OVERWRITTEN.
 */
package adventureworks
package production
package productreview

import adventureworks.Defaulted
import adventureworks.production.product.ProductId
import adventureworks.public.Name
import java.time.LocalDateTime
import play.api.libs.json.JsObject
import play.api.libs.json.JsResult
import play.api.libs.json.JsValue
import play.api.libs.json.Json
import play.api.libs.json.OFormat
import scala.util.Try

/** This class corresponds to a row in table `production.productreview` which has not been persisted yet */
case class ProductreviewRowUnsaved(
  /** Product identification number. Foreign key to Product.ProductID.
      Points to [[product.ProductRow.productid]] */
  productid: ProductId,
  /** Name of the reviewer. */
  reviewername: Name,
  /** Default: now()
      Date review was submitted. */
  reviewdate: Defaulted[LocalDateTime],
  /** Reviewer's e-mail address. */
  emailaddress: String,
  /** Product rating given by the reviewer. Scale is 1 to 5 with 5 as the highest rating. */
  rating: Int,
  /** Reviewer's comments */
  comments: Option[String],
  /** Default: now() */
  modifieddate: Defaulted[LocalDateTime]
) {
  def unsafeToRow(productreviewid: ProductreviewId): ProductreviewRow =
    ProductreviewRow(
      productreviewid = productreviewid,
      productid = productid,
      reviewername = reviewername,
      reviewdate = reviewdate match {
                     case Defaulted.UseDefault => sys.error("cannot produce row when you depend on a value which is defaulted in database")
                     case Defaulted.Provided(value) => value
                   },
      emailaddress = emailaddress,
      rating = rating,
      comments = comments,
      modifieddate = modifieddate match {
                       case Defaulted.UseDefault => sys.error("cannot produce row when you depend on a value which is defaulted in database")
                       case Defaulted.Provided(value) => value
                     }
    )
}
object ProductreviewRowUnsaved {
  implicit val oFormat: OFormat[ProductreviewRowUnsaved] = new OFormat[ProductreviewRowUnsaved]{
    override def writes(o: ProductreviewRowUnsaved): JsObject =
      Json.obj(
        "productid" -> o.productid,
        "reviewername" -> o.reviewername,
        "reviewdate" -> o.reviewdate,
        "emailaddress" -> o.emailaddress,
        "rating" -> o.rating,
        "comments" -> o.comments,
        "modifieddate" -> o.modifieddate
      )
  
    override def reads(json: JsValue): JsResult[ProductreviewRowUnsaved] = {
      JsResult.fromTry(
        Try(
          ProductreviewRowUnsaved(
            productid = json.\("productid").as[ProductId],
            reviewername = json.\("reviewername").as[Name],
            reviewdate = json.\("reviewdate").as[Defaulted[LocalDateTime]],
            emailaddress = json.\("emailaddress").as[String],
            rating = json.\("rating").as[Int],
            comments = json.\("comments").toOption.map(_.as[String]),
            modifieddate = json.\("modifieddate").as[Defaulted[LocalDateTime]]
          )
        )
      )
    }
  }
}
